//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinarySearchTreeNamesDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeNode
    {
        public int ID { get; set; }
        public string Element { get; set; }
        public int Left { get; set; }
        public int Right { get; set; }
    }
}
